### ISSUE TITLE
Support for creating weapons in the cracked version

### ISSUE THREAD

**Issue by Bashkir15** [CapitaineToinon/Gadgetlemage#2]
Currently Spawning of Black Knight Items, manual or knight death, will crash the cracked version of the game. All other features like the deletion of shield seem to work fine.

**Comment by eltharynd** [comment]
buy the game DansGame

**Comment by eltharynd** [comment]
^ I'm JK, you know...

**Comment by CapitaineToinon** [comment]
Should be fixed by [0bbd3240f10a4de35f920a8a8680b4e848b99d49](https://github.com/CapitaineToinon/Gadgetlemage/commit/0bbd3240f10a4de35f920a8a8680b4e848b99d49)
